# Generated by Django 5.0.1 on 2024-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='website/')),
                ('author', models.TextField(default=None, null=True)),
                ('status', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
