# Generated by Django 5.0.1 on 2024-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
